site_name: Estrela Guia
site_description: Assistente virtual astrológica com Python, ChatGPT e tool calling
site_author: Estrela Guia Team
repo_url: https://github.com/thalisonwilker/estrela-guia
repo_name: estrela-guia

theme:
  name: material
  language: pt-BR
  palette:
    # Paleta de cores com tema claro/escuro
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Mudar para modo escuro
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Mudar para modo claro
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  # Extensões para código
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  
  # Extensões para diff de código (estilo Git)
  - pymdownx.critic:
      mode: view
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  
  # Outras extensões úteis
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - tables
  - footnotes
  - abbr

plugins:
  - search:
      lang: pt
  - info


# Estrutura de navegação
nav:
  - Início: index.md
  - Workflow de Publicação: workflow.md
  - Ferramentas:
    - Horóscopo: tools-horoscopo.md

# Configurações extras
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yourusername/estrela-guia
    - icon: fontawesome/brands/python
      link: https://python.org
  
  # Configuração de análise (opcional)
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY

# Configurações de copyright
copyright: Copyright &copy; Python Norte, julho de 2025